runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  X_WEATHER_API_KEY: "89bb0478aamsh0bcbdd01be5abdfp149f0ejsn5b83f6311b6a"

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3.9
